name = "v0-meeting"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[env.production]
compatibility_flags = ["nodejs_compat"]

[env.preview]  
compatibility_flags = ["nodejs_compat"]
